/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kps_dsk_DSKController */

#ifndef _Included_com_kps_dsk_DSKController
#define _Included_com_kps_dsk_DSKController
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     com_kps_dsk_DSKController
	* Method:    nativeStaticInitialise
	* Signature: ()V
	*/
	JNIEXPORT void JNICALL Java_com_kps_dsk_DSKController_nativeStaticInitialise
		(JNIEnv*, jclass);

	/*
	* Class:     com_kps_dsk_DSKController
	* Method:    nativeInitialise
	* Signature: (Lcom/kps/dsk/DSKInitParameters;Lcom/kps/dsk/DSKCanvas;)V
	*/
	JNIEXPORT void JNICALL Java_com_kps_dsk_DSKController_nativeInitialise
		(JNIEnv* , jobject, jobject, jobject);

	/*
	* Class:     com_kps_dsk_DSKController
	* Method:    nativeGetDuration
	* Signature: ()J
	*/
	JNIEXPORT jlong JNICALL Java_com_kps_dsk_DSKController_nativeGetDuration
		(JNIEnv*, jobject);

	/*
	* Class:     com_kps_dsk_DSKController
	* Method:    nativeGetTime
	* Signature: ()J
	*/
	JNIEXPORT jlong JNICALL Java_com_kps_dsk_DSKController_nativeGetTime
		(JNIEnv*, jobject);

	/*
	* Class:     com_kps_dsk_DSKController
	* Method:    nativeSetTime
	* Signature: (J)V
	*/
	JNIEXPORT void JNICALL Java_com_kps_dsk_DSKController_nativeSetTime
		(JNIEnv*, jobject, jlong);

	/*
	* Class:     com_kps_dsk_DSKController
	* Method:    nativeSetSize
	* Signature: (II)J
	*/
	JNIEXPORT void JNICALL Java_com_kps_dsk_DSKController_nativeSetSize
		(JNIEnv*, jobject, jint, jint);

	/*
	* Class:     com_kps_dsk_DSKController
	* Method:    nativePlay
	* Signature: ()V
	*/
	JNIEXPORT void JNICALL Java_com_kps_dsk_DSKController_nativePlay
		(JNIEnv*, jobject);

	/*
	* Class:     com_kps_dsk_DSKController
	* Method:    nativePause
	* Signature: ()V
	*/
	JNIEXPORT void JNICALL Java_com_kps_dsk_DSKController_nativePause
		(JNIEnv*, jobject);

	/*
	* Class:     com_kps_dsk_DSKController
	* Method:    nativeStop
	* Signature: ()V
	*/
	JNIEXPORT void JNICALL Java_com_kps_dsk_DSKController_nativeStop
		(JNIEnv*, jobject);

	/*
	* Class:     com_kps_dsk_DSKController
	* Method:    nativePaint
	* Signature: (Lcom/kps/dsk/DSKCanvas;)V
	*/
	JNIEXPORT void JNICALL Java_com_kps_dsk_DSKController_nativePaint
		(JNIEnv*, jobject, jobject);

	/*
	* Class:     com_kps_dsk_DSKController
	* Method:    nativeGetVideoSize
	* Signature: ()Ljava/awt/Dimension;
	*/
	JNIEXPORT jobject JNICALL Java_com_kps_dsk_DSKController_nativeGetVideoSize
		(JNIEnv*, jobject);

#ifdef __cplusplus
}
#endif
#endif
